apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app-pod
      version: v1
  template:
    metadata:
      labels:
        name: app-pod
        version: v1
      # annotations:
      #   someKey: someValue  
    spec:
      containers:
      - name: app-container
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent
        ports:
        - name: app-port
          #name shld be 16 chars or less
          containerPort: 3000
        env:
         - name: BGG_DB_USER
           value: root
         - name: BGG_DB_HOST
           value: db-svc
        envFrom:
        - secretRef:
            name: db-secret
        livenessProbe:
          httpGet:
            path: /healthz
            port: app-port
          periodSeconds: 30
          failureThreshold: 3
---
apiVersion: v1
kind: Service
# round robin
metadata:
  name: app-svc
  labels:
    name: app-svc
spec:
  type: LoadBalancer
  # type: ClusterIP
  selector: 
    name: app-pod
    version: v1
  ports:
  - name: app-svc-port
    port: 80
    targetPort: app-port

