---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nwdb-pvc
  labels:
    name: nwdb-pvc
  # annotations:
  #   someKey: someValue
spec:
  accessModes:
  - ReadWriteOnce
  #kubectl get storageclass
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi
